// Extracts the vector paths from Nevila's logo PDF into SVG. Run: node tools/pdf-logo.mjs <pdf>
import { readFileSync, writeFileSync } from "node:fs";
import { inflateSync } from "node:zlib";

// Pull the one page content stream out of the PDF.
function content(file) {
  const buf = readFileSync(file);
  for (let i = 0; (i = buf.indexOf("stream", i)) !== -1; ) {
    if (buf.subarray(i - 3, i).toString("latin1") === "end") { i += 6; continue; }
    let st = i + 6;
    if (buf[st] === 13) st++;
    if (buf[st] === 10) st++;
    const end = buf.indexOf("endstream", st);
    try {
      const out = inflateSync(buf.subarray(st, end));
      if (/\sc\s|\sre\s/.test(out.toString("latin1"))) return out.toString("latin1");
    } catch { /* not this one */ }
    i = end + 9;
  }
  throw new Error("no content stream with path operators");
}

// Naive CMYK is too dull for brand colour, so scale toward the Adobe-rendered appearance.
const cmyk = (c, m, y, k) => "#" + [(1 - c) * (1 - k), (1 - m) * (1 - k), (1 - y) * (1 - k)]
  .map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("");

const mul = (a, b) => [
  a[0] * b[0] + a[1] * b[2], a[0] * b[1] + a[1] * b[3],
  a[2] * b[0] + a[3] * b[2], a[2] * b[1] + a[3] * b[3],
  a[4] * b[0] + a[5] * b[2] + b[4], a[4] * b[1] + a[5] * b[3] + b[5],
];
const apply = (m, x, y) => [m[0] * x + m[2] * y + m[4], m[1] * x + m[3] * y + m[5]];

export function convert(file) {
  const tokens = content(file).split(/\s+/);
  const num = (s) => parseFloat(s);
  let ctm = [1, 0, 0, 1, 0, 0], stack = [], fill = "#000000";
  let d = "", cur = [0, 0], start = [0, 0];
  const out = [];
  const box = [Infinity, Infinity, -Infinity, -Infinity];
  const pt = (x, y) => {
    const [px, py] = apply(ctm, x, y);
    box[0] = Math.min(box[0], px); box[1] = Math.min(box[1], py);
    box[2] = Math.max(box[2], px); box[3] = Math.max(box[3], py);
    return `${+px.toFixed(2)} ${+py.toFixed(2)}`;
  };

  for (let i = 0; i < tokens.length; i++) {
    const op = tokens[i], a = (n) => num(tokens[i - n]);
    if (op === "q") stack.push(ctm.slice());
    else if (op === "Q") ctm = stack.pop() ?? ctm;
    else if (op === "cm") ctm = mul([a(6), a(5), a(4), a(3), a(2), a(1)], ctm);
    else if (op === "k") fill = cmyk(a(4), a(3), a(2), a(1));
    else if (op === "m") { cur = start = [a(2), a(1)]; d += `M${pt(...cur)}`; }
    else if (op === "l") { cur = [a(2), a(1)]; d += `L${pt(...cur)}`; }
    else if (op === "c") { d += `C${pt(a(6), a(5))} ${pt(a(4), a(3))} ${pt(a(2), a(1))}`; cur = [a(2), a(1)]; }
    else if (op === "v") { d += `C${pt(...cur)} ${pt(a(4), a(3))} ${pt(a(2), a(1))}`; cur = [a(2), a(1)]; }
    else if (op === "y") { d += `C${pt(a(4), a(3))} ${pt(a(2), a(1))} ${pt(a(2), a(1))}`; cur = [a(2), a(1)]; }
    else if (op === "h") { d += "Z"; cur = start; }
    else if (op === "re") {
      const [x, y, w, h] = [a(4), a(3), a(2), a(1)];
      d += `M${pt(x, y)}L${pt(x + w, y)}L${pt(x + w, y + h)}L${pt(x, y + h)}Z`;
    } else if (op === "f" || op === "f*" || op === "b" || op === "B") {
      if (d) out.push({ fill, d });
      d = "";
    } else if (op === "n") d = "";
  }
  return { paths: out, box };
}

const file = process.argv[2];
const { paths, box } = convert(file);
const byFill = {};
for (const p of paths) (byFill[p.fill] ??= []).push(p.d);
console.log("bbox", box.map((v) => +v.toFixed(1)).join(", "));
for (const [f, list] of Object.entries(byFill)) console.log(f, list.length, "path(s),", list.join("").length, "chars");
writeFileSync("/tmp/logo-paths.json", JSON.stringify({ box, byFill }, null, 1));

// ---- emit ----------------------------------------------------------------
// Naive CMYK is too hot for brand colour; these are the Adobe-rendered equivalents.
const BRAND = { navy: "#262261", orange: "#f47b20" };
const H = 992.126;

// Flip PDF's y-up axis into SVG's y-down and drop to one decimal.
const flip = (d) => d.replace(/(-?[\d.]+) (-?[\d.]+)/g, (_, x, y) => `${+(+x).toFixed(1)} ${+(H - y).toFixed(1)}`);

const navy = [...(byFill["#00007d"] ?? []), ...(byFill["#00037e"] ?? [])].map(flip);
const orange = (byFill["#ff580a"] ?? []).map(flip);
// Ordered by the classification above: left stem, lower swoosh, upper swoosh, right tip.
const [stem, lower, upper, tip] = navy;

writeFileSync("assets/js/site/logo-paths.js",
  `// Generated by tools/pdf-logo.mjs from the source logo PDF. Do not hand-edit.\n` +
  `export const MARK = {\n` +
  `  stem: "${stem}",\n  lower: "${lower}",\n  upper: "${upper}",\n  tip: "${tip}",\n` +
  `};\nexport const VIEWBOX = "10 38 1100 840";\nexport const BRAND = ${JSON.stringify(BRAND)};\n`);

writeFileSync("assets/img/logo-full.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1133.9 992.1" role="img" aria-label="Nevila Samarxhi Akulli — design">` +
  navy.map((d) => `<path fill="${BRAND.navy}" d="${d}"/>`).join("") +
  orange.map((d) => `<path fill="${BRAND.orange}" d="${d}"/>`).join("") +
  `</svg>`);

console.log("wrote assets/js/site/logo-paths.js and assets/img/logo-full.svg");

// Social card. SVG for the repo, PNG because no social platform rasterises SVG.
const SANS = "Inter Tight, Helvetica Neue, Arial, sans-serif";
const s = 200 / 1100;
const og = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630" role="img" aria-label="Nevila Samarxhi Akulli">`
  + `<rect width="1200" height="630" fill="#f9f9fb"/>`
  + `<circle cx="1010" cy="150" r="190" fill="${BRAND.orange}" opacity=".14"/>`
  + `<g transform="translate(${(80 - 10 * s).toFixed(1)} ${(70 - 38 * s).toFixed(1)}) scale(${s.toFixed(4)})">`
  + [stem, lower, upper, tip].map((d) => `<path fill="${BRAND.navy}" d="${d}"/>`).join("") + `</g>`
  + `<text x="80" y="360" font-family="${SANS}" font-weight="600" font-size="82" letter-spacing="-3" fill="${BRAND.navy}">Nevila Samarxhi Akulli</text>`
  + `<text x="80" y="430" font-family="Instrument Serif, Georgia, Times New Roman, serif" font-style="italic" font-size="46" fill="${BRAND.orange}">Dizajn grafik &amp; web</text>`
  + `<rect x="80" y="495" width="180" height="5" fill="${BRAND.navy}"/>`
  + `<text x="80" y="565" font-family="${SANS}" font-size="30" letter-spacing="4" fill="${BRAND.navy}" opacity=".55">TIRANË, SHQIPËRI</text>`
  + `</svg>`;
writeFileSync("assets/img/og.svg", og);

const sharp = (await import("sharp")).default;
await sharp(Buffer.from(og), { density: 200 }).resize(1200, 630).png({ compressionLevel: 9 }).toFile("assets/img/og.png");
console.log("wrote assets/img/og.svg and og.png");

// Favicon: her own mark, on a light plate so it reads on a light or a dark tab bar.
const fs2 = 40 / 1100;
writeFileSync("assets/img/favicon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" role="img" aria-label="N design">`
  + `<rect width="48" height="48" rx="11" fill="#f9f9fb"/>`
  + `<g transform="translate(${(4 - 10 * fs2).toFixed(2)} ${(8.7 - 38 * fs2).toFixed(2)}) scale(${fs2.toFixed(5)})">`
  + [stem, lower, upper, tip].map((d) => `<path fill="${BRAND.navy}" d="${d}"/>`).join("")
  + `</g></svg>`);
console.log("wrote assets/img/favicon.svg");
